CountdownToTomorrowland/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from travelmap.views import ItineraryDelete

try:
    from django.conf.urls import patterns, url
except ImportError:
    # Django < 1.4
    from django.conf.urls.defaults import patterns, url
from social.utils import setting_name
extra = getattr(settings, setting_name('TRAILING_SLASH'), True) and '/' or ''

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'travelmap.views.map', name="map_detail"),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^logout/$', 'countdown.views.logout', name="logout"),
    url(r'^new_itinerary/$', 'travelmap.views.new_itinerary', name="new_itinerary"),
    url(r'^edit_itinerary/(?P<username>[-\w]+)/$', 'travelmap.views.edit_itinerary', name="edit_itinerary"),
    url(r'^itinerary/(?P<username>[-\w]+)/$', 'travelmap.views.itinerary_detail', name="itinerary_detail"),
    url(r'^itinerary/(?P<pk>\d+)/delete/$', ItineraryDelete.as_view(), name="delete_itinerary"),
    url(r'^get_users/$', 'travelmap.views.get_users', name="get_users"),
    url(r'^about/$', 'countdown.views.about', name="about"),
    url(r'^feedback/$', 'countdown.views.feedback', name="feedback")



]

travelmap/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class Itinerary(models.Model):
    GLOBAL_JOURNEY_PACKAGE_TYPES = (
        ('Flight Package', 'Flight Package'),
        ('Train Package', 'Train Package'),
        ('Hotel Package', 'Hotel Package'),
        ('Day of Madness', 'Day of Madness'),
        ('Discover Europe', 'Discover Europe'),
    )

    HOTELS = (
        ('Bedford','Bedford'),
        ('Best Western County House','Best Western County House'),
        ('Bloom!','Bloom!'),
        ('Colonies Hotel','Colonies Hotel'),
        ('Courtyard by Marriott','Courtyard by Marriott'),
        ('Gresham Belson','Gresham Belson'),
        ('Holiday Inn Airport','Holiday Inn Airport'),
        ('Ibis Styles Louise','Ibis Styles Louise'),
        ('Manos Premier','Manos Premier'),
        ('Martin\'s EU','Martin\'s EU'),
        ('Meininger','Meininger'),
        ('Metropole','Metropole'),
        ('Pentahotel Brussels Airport','Pentahotel Brussels Airport'),
        ('Pentahotel Brussels City Center','Pentahotel Brussels City Center'),
        ('Radisson Blu le Royal','Radisson Blu le Royal'),
        ('Ramada Brussels Woluwe','Ramada Brussels Woluwe'),
        ('Sheraton Brussels City','Sheraton Brussels City'),
        ('Siru Hotel','Siru Hotel'),
        ('Sofitel Louise','Sofitel Louise'),
        ('Stanhope','Stanhope'),
        ('The Hotel','The Hotel'),
        ('Van Der Valk Airport','Van Der Valk Airport'),
        ('Warwick Barsey','Warwick Barsey'),
    )

    DREAMVILLE_TYPES = (
        ('Magnificent Greens','Magnificent Greens'),
        ('Friendship Garden','Friendship Garden'),
        ('Fabulous Friendship Garden','Fabulous Friendship Garden'),
        ('Easy Tent','Easy Tent'),
        ('Fabulous Easy Tent','Fabulous Easy Tent'),
        ('Relax Room','Relax Room'),
        ('DreamLodge','DreamLodge'),
        ('Fabulous DreamLodge','Fabulous DreamLodge'),
        ('DreamVille Cabana','DreamVille Cabana'),
        ('Exclusive Mansion','Exclusive Mansion'),
    )

    user = models.OneToOneField(User)
    departure_city = models.CharField(max_length=255, blank=False)
    arrival_city = models.CharField(max_length=255, blank=False)
    arrival_lat = models.FloatField()
    departure_lat = models.FloatField()
    arrival_lng = models.FloatField()
    departure_lng = models.FloatField()
    attending_fri = models.BooleanField(default=True, verbose_name='Friday, July 24')
    attending_sat = models.BooleanField(default=True, verbose_name='Saturday, July 25')
    attending_sun = models.BooleanField(default=True, verbose_name='Sunday, July 25')
    global_journey = models.BooleanField(default=False)
    global_journey_type = models.CharField(max_length=255, choices=GLOBAL_JOURNEY_PACKAGE_TYPES, blank=True)
    hotel_package = models.BooleanField(default=False)
    hotel = models.CharField(max_length=255, choices=HOTELS, blank=True)
    dreamville_package = models.BooleanField(default=False)
    dreamville = models.CharField(max_length=255, choices=DREAMVILLE_TYPES, blank=True)
    comments = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return str(self.user)

    # def save(self, *args, **kwargs):
    #     if not self.id:
    #         self.created = datetime.datetime.today()
    #
    #     self.updated = datetime.datetime.today()
    #     return super(Itinerary, self).save(*args, **kwargs)

travelmap/forms.py
from django import forms
from travelmap.models import Itinerary
from django.forms import widgets
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, ButtonHolder, Field, HTML
from crispy_forms.bootstrap import InlineField, InlineCheckboxes, FormActions

# allows a user to create a Tomorrowland Itinerary
class ItineraryForm(forms.ModelForm):
    class Meta:
        model = Itinerary
        fields = ['departure_city',
                  'arrival_city',
                  'attending_fri',
                  'attending_sat',
                  'attending_sun',
                  'global_journey',
                  'global_journey_type',
                  'hotel_package',
                  'hotel',
                  'dreamville_package',
                  'dreamville',
                  'comments',
                  'arrival_lat',
                  'arrival_lng',
                  'departure_lat',
                  'departure_lng'
        ]

        exclude = ['user',
                   'updated'
        ]

        widgets = {
            'arrival_lat': forms.HiddenInput(),
            'arrival_lng': forms.HiddenInput(),
            'departure_lat': forms.HiddenInput(),
            'departure_lng': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super(ItineraryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(

            Fieldset(
                'Departure and Arrival Info',
                'departure_city',
                'arrival_city'
            ),
            Fieldset(
                'Days Attending',
                InlineField(
                    'attending_fri',
                    'attending_sat',
                    'attending_sun'
                )
            ),
            Fieldset(
                'Accommodations Info',
                'global_journey',
                'global_journey_type',
                'dreamville_package',
                'dreamville',
                'hotel_package',
                'hotel',
            ),
            Field('comments', placeholder='Add any additional comments you would like '
                                          'to share with other Redditors about your Tomorrowland travel plans.'),
            'arrival_lat',
            'arrival_lng',
            'departure_lat',
            'departure_lng',


            FormActions(
                Submit('save', 'Save Itinerary', css_class='btn btn-tomorrowland')
            )


        )

    def clean(self):
        cleaned_data = super(ItineraryForm, self).clean()
        departure_lat = cleaned_data.get("departure_lat")
        departure_lng = cleaned_data.get("departure_lng")
        arrival_lat = cleaned_data.get("arrival_lat")
        arrival_lng = cleaned_data.get("arrival_lng")

        if departure_lat == 91 or departure_lng == 181:
            self.add_error('departure_city', "The Departure City you entered was not a valid location")

        if arrival_lat == 91 or arrival_lng == 181:
            self.add_error('arrival_city', "The Arrival City you entered was not a valid location")


travelmap/views.py
from django.shortcuts import render, get_object_or_404
from travelmap.forms import ItineraryForm
from travelmap.models import Itinerary
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.contrib import messages
from django.views.generic import CreateView, DeleteView
import datetime
import json

def itinerary_detail(request, username):
    itinerary = get_object_or_404(Itinerary, user__username=username)
    context = {'itinerary': itinerary}

    return render(request, 'travelmap/itinerary_detail.html', context)

def get_users(request):
    if request.is_ajax():
        data = serializers.serialize("json",
                                  Itinerary.objects.all(),
                                  fields=('user',
                                          'departure_city',
                                          'arrival_city',
                                          'attending_fri',
                                          'attending_sat',
                                          'attending_sun',
                                          'global_journey',
                                          'global_journey_type',
                                          'hotel_package',
                                          'hotel',
                                          'dreamville_package',
                                          'dreamville',
                                          'comments',
                                          'arrival_lat',
                                          'arrival_lng',
                                          'departure_lat',
                                          'departure_lng'
                                  ),
                                  use_natural_foreign_keys=True)

        json_data = json.dumps(data)

        return HttpResponse(data, content_type='application/json')
    else:
        raise Http404
def map(request):
    users = serializers.serialize("json",
                                  Itinerary.objects.all(),
                                  fields=('user',
                                          'departure_city',
                                          'arrival_city',
                                          'attending_fri',
                                          'attending_sat',
                                          'attending_sun',
                                          'global_journey',
                                          'global_journey_type',
                                          'hotel_package',
                                          'hotel',
                                          'dreamville_package',
                                          'dreamville',
                                          'comments',
                                          'arrival_lat',
                                          'arrival_lng',
                                          'departure_lat',
                                          'departure_lng'
                                  ),
                                  use_natural_foreign_keys=True)
    users = json.dumps(users)

    context = {'users': users}
    return render(request, 'travelmap/map.html', context)


@login_required()
def new_itinerary(request):
    action = 'new_itinerary/'

    if Itinerary.objects.filter(user=request.user):
        url = reverse('edit_itinerary', kwargs={'username': request.user.username})
        return HttpResponseRedirect(url)

    if request.method == 'POST':
        form = ItineraryForm(request.POST)
        print "POST"

        # validate form
        if form.is_valid():
            itinerary = form.save(commit=False)
            itinerary.user = request.user
            itinerary.created = datetime.datetime.today()
            itinerary.save()
            messages.success(request, "Itinerary was successfully added to the map!")
            return HttpResponseRedirect(reverse('edit_itinerary', kwargs={'username': request.user.username}))

        else:
            messages.error(request, "Something went wrong. Check your Departure and Arrival cities and try again")
    else:
        # display form
        form = ItineraryForm()
        print "GET"

    # Bad form or no form supplied...
    # Render the form with error messages
    return render(request, 'travelmap/itinerary.html', {'form': form, 'action': action})

@login_required()
def edit_itinerary(request, username):
    user = request.user
    action = "edit_itinerary/%s/" % (username,)
    edit = True

    # Make sure user is editing his own itinerary!
    if user.username != username:
        raise Http404

    itinerary = get_object_or_404(Itinerary, user__username=username)

    if request.method == 'POST':
        form = ItineraryForm(request.POST, instance=itinerary)

        if form.is_valid():
            form.save()
            messages.success(request, "Itinerary successfully updated!")
            return HttpResponseRedirect(reverse('itinerary_detail', kwargs={'username': user.username}))
        else:
            messages.error(request, "Something went wrong. Make sure your Departure/Arrival locations are "
                                    "valid and try again.")

    else:
        # request was not POST, so display the form instance
        form = ItineraryForm(instance=itinerary)

    return render(request, 'travelmap/itinerary.html', {'form': form, 'action': action, 'edit': edit})


class ItineraryDelete(DeleteView):
    model = Itinerary
    success_url = reverse_lazy('map_detail')

    def get_object(self, queryset=None):
        # Hook to ensure object is owned by request.user
        obj = super(ItineraryDelete, self).get_object()
        if not obj.user == self.request.user:
            raise Http404

        return obj

templates/travelmap/itinerary.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block links %}
   <link rel="stylesheet" href="{% static "css/formstyles.css" %}">
{% endblock %}

{% block content %}
<form id="itinerary_form" method="post" action="/{{ action }}">

    {% crispy form %}

</form>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
    <script type="text/javascript" src="{% static 'js/autocomplete.js' %}"></script>
    <script>
        $(document).ready(function() {

            $('#div_id_global_journey_type,#div_id_hotel,#div_id_dreamville').each(function() {
                $(this).hide();
            });

            {% if edit %}
                if ($('#id_global_journey').is(':checked')) $('#div_id_global_journey_type').show();
                if ($('#id_hotel_package').is(':checked')) $('#div_id_hotel').show();
                if ($('#id_dreamville_package').is(':checked')) $('#div_id_dreamville').show();
                $('.form-actions').append('<a href="{% url 'delete_itinerary' user.itinerary.id %}" class="btn btn-default"><i class="fa fa-trash-o"></i> Delete</a>');


            {% endif %}

            $('#id_global_journey').change(function() {
                if ($(this).is(':checked')) {
                    $('#div_id_global_journey_type').show();
                } else {
                    $('#div_id_global_journey_type').hide();
                    $('#id_global_journey_type').prop('selectedIndex', 0);
                }
            });

            $('#id_hotel_package').change(function() {
                if ($(this).is(':checked')) {
                    $('#div_id_hotel').show();
                } else {
                    $('#div_id_hotel').hide();
                    $('#id_hotel').prop('selectedIndex', 0);
                }
            });

            $('#id_dreamville_package').change(function() {
                if ($(this).is(':checked')) {
                    $('#div_id_dreamville').show();
                } else {
                    $('#div_id_dreamville').hide();
                    $('#id_dreamville').prop('selectedIndex', 0);
                }
            });

            $('#id_global_journey_type').change(function() {
                var option = $('#id_global_journey_type option:selected').text();
                console.log(option);
                if(option == "Hotel Package") {
                    console.log("yes");
                    $('#id_hotel_package').prop('checked', true).change();
                } else {
                    $('#id_hotel_package').prop('checked', false).change();
                }
            });

            initializeAutocomplete('id_departure_city', 'id_arrival_city');

            google.maps.event.addListener(autocompleteArray[0], 'place_changed', onDepartureCityChanged);
            google.maps.event.addListener(autocompleteArray[1], 'place_changed', onArrivalCityChanged);





        });

    </script>
{% endblock %}

templates/travelmap/itinerary_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class=" jumbotron form-signin col-md-6">
            <form id="delete_itinerary_form" method="post">
                {% csrf_token %}
                <h4>Are you sure you want to delete your itinerary?</h4>

                <input class='btn btn-lg btn-danger btn-block' type="submit" name="submit" value="Delete" />
                <a href="{% url 'edit_itinerary' user.username %}" class="btn btn-lg btn-block btn-default">Cancel</a>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>

{% endblock %}

templates/travelmap/itinerary_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/itinerary_detail.css' %}">
{% endblock %}

{% block content %}
    <div>
        <div>
            <h1>{{ itinerary.user}}'s Journey</h1>
        </div>
        <div>
            <a class="btn btn-tomorrowland" href="https://www.reddit.com/message/compose?to={{ itinerary.user }}&subject=&message=">Message on Reddit &nbsp;&nbsp;<i class="fa fa-envelope"></i></a>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title tml">Departure and Arrival Info</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-2"><i class="fa fa-map-marker"></i> <strong>Departure City:</strong></div>
                    <div class="col-md-10">{{ itinerary.departure_city }}</div>
                </div>
                <div class="row">
                    <div class="col-md-2"><i class="fa fa-map-marker"></i> <strong>Arrival City:</strong></div>
                    <div class="col-md-10">{{ itinerary.arrival_city }}</div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title tml">Days Attending</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-1 col-md-1"><strong>Friday:</strong></div>
                    <div class="col-sm-1 col-md-1">{% if itinerary.attending_fri %}<i class="fa fa-check-circle"></i>{% else %}<i class="fa fa-times"></i>{% endif %}</div>
                </div>
                <div class="row">
                    <div class="col-sm-1 col-md-1"><strong>Saturday:</strong></div>
                    <div class="col-sm-1 col-md-1">{% if itinerary.attending_sat %}<i class="fa fa-check-circle"></i>{% else %}<i class="fa fa-times"></i>{% endif %}</div>
                </div>
                <div class="row">
                    <div class="col-sm-1"><strong>Sunday:</strong></div>
                    <div class="col-sm-1">{% if itinerary.attending_sun %}<i class="fa fa-check-circle"></i>{% else %}<i class="fa fa-times"></i>{% endif %}</div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title tml">Accommodations Info</h3>
            </div>
            <div class="panel-body">
                {% if itinerary.global_journey %}
                <div class="row">
                    <div class="col-sm-2 col-md-2"><strong>Global Journey Package:</strong></div>
                    <div class="col-sm-10 col-md-6">{{ itinerary.global_journey_type }}</div>
                </div>
                {% endif %}
                {% if itinerary.hotel_package %}
                <div class="row">
                    <div class="col-sm-2 col-md-2"><strong>Hotel Package:</strong></div>
                    <div class="col-sm-10 col-md-6">{{ itinerary.hotel }}</div>
                </div>
                {% endif %}
                {% if itinerary.dreamville_package %}
                    <div class="row">
                        <div class="col-md-2"><strong>Dreamville Package:</strong></div>
                        <div class="col-md-6">{{ itinerary.dreamville }}</div>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title tml">Comments</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12">{{ itinerary.comments }}</div>
                </div>
            </div>
        </div>
    </div>






{% endblock %}

templates/travelmap/map.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div id="wrapper">

    <div id="map-canvas"></div>
    <div id="countdown" data-date="2015-07-24 12:00:00"></div>
    </div>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVSeOgiFX1LF2TkLwzFuxjkEWjl1eFc7M"></script>
<script type="text/javascript" src="{% static 'js/oms.min.js' %}"></script>
<script>
var map;
var autocomplete;
var places;
var markers = [];
var flightPaths = [];
var flightPathsOn = true;
var json_data;
var users;
var image = '{% static 'img/map_icon_sm.png' %}';
var logo = '{% static 'img/icon_sm.png' %}';
var styles = [
    {
        "stylers":[
            {
                "visibility":"simplified"
            }
        ]
    },
    {
        "stylers":[
            {
                "color":"#131314"
            }
        ]
    },
    {
        "featureType":"water",
        "stylers":[
            {
                "color":"#131313"},
            {
                "lightness":7
            }
        ]
    },
    {
        "elementType":"labels.text.fill",
        "stylers":[
            {
                "visibility":"on"
            },
            {
                "lightness":25
            }
        ]
    },
    {
        "featureType": "administrative",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#831042"
            }
        ]
    },
    {
        "featureType": "administrative.locality",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#D86D9C"
            }
        ]
    }

];

function init() {
    var tomorrowlandMarker;
    var mapOptions = {
        zoom: 3,
        minZoom: 3,
        streetViewControl: false,
        mapTypeControl: false,
        panControl: false,
        center: new google.maps.LatLng(51.091448, 4.385369),
        styles: styles

    };
    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

    tomorrowlandMarker = new google.maps.Marker({
                position: new google.maps.LatLng(51.091448, 4.385369),
                map: map,
                icon: logo
    });
    getUsers();


}

function populateMap(users) {
        var departureLatLng;
        var arrivalLatLng;
        var flightCoords;
        var infoWindow;
        var windowContent;
        var marker;
        var user;
        var daysAttending;
        var oms = new OverlappingMarkerSpiderfier(map,{
            markersWontMove: true,
            markersWontHide: true,
            keepSpiderfied: true
        });

        infoWindow = new google.maps.InfoWindow({
            content: "Holding..."
        });

        for (var i = 0; i < users.length; i++) {
            user = users[i].fields.user[0];
            departureLatLng = new google.maps.LatLng(users[i].fields.departure_lat, users[i].fields.departure_lng);
            arrivalLatLng = new google.maps.LatLng(users[i].fields.arrival_lat, users[i].fields.arrival_lng);

            // Place Marker on Departure point
            markers[i] = new google.maps.Marker({
                position: departureLatLng,
                map: map,
                title: user,
                icon: image
            });
            console.log(markers[i]);
            marker = markers[i];

            // Create flight path polyline
            flightCoords = [departureLatLng, arrivalLatLng];
            flightPaths[i] = new google.maps.Polyline({
                path: flightCoords,
                geodesic: true,
                strokeColor: '#BB4478',
                strokeOpacity: 1.0,
                strokeWeight: 2
            });
            flightPaths[i].setMap(map);

            // Create Info Window
            windowContent = '<div id="infowindowContent">' +
                    '<h4>' + user + '</h4>' +
                    '<div>Departing City: ' + users[i].fields.departure_city + '</div>' +
                    '<div>Arrival City: ' + users[i].fields.arrival_city + '</div>' +
                    '<a href="/itinerary/' + user + '" class="btn btn-block btn-tomorrowland">View Journey</a></div>';

            oms.addMarker(marker);


            google.maps.event.addListener(marker, 'click', (function (marker, windowContent) {
                return function () {
                    infoWindow.setContent(windowContent);
                    infoWindow.open(map, marker);
                };

            })(marker, windowContent));


        }
    }

function onPlaceChanged() {
    var place = autocomplete.getPlace();
    if (place.geometry) {
        map.panTo(place.geometry.location);
        map.setZoom(15);
    } else {
        document.getElementById('search').placeholder = 'Enter a City';
    }
}

function getUsers() {
    var url = {% url 'get_users' %};
    $.getJSON(url)
            .done(function(data) {
                populateMap(data);

            })
            .fail(function() {
                console.log("Error Retrieving Users...");
            });
}

function hideFlightPaths() {
    for (var i = 0; i < flightPaths.length; i++) {
        flightPaths[i].setMap(null);
    }
}

function displayFlightPaths() {
    for (var i = 0; i < flightPaths.length; i++ ) {
        flightPaths[i].setMap(map);
    }
}

$(document).ready(function() {
    init();
    $('#toggle-paths').on('click', function() {

        if (flightPathsOn) {
            $(this).html("Show Flight Paths");
            hideFlightPaths();
            flightPathsOn = false;
        } else {
            $(this).html("Hide FlightPaths");
            displayFlightPaths();
            flightPathsOn = true;
        }


    });
});
</script>
{% endblock %}

templates/travelmap/map_navbar.html
    <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>